### ISSUE TITLE
Feature Request: Registry Explorer

### ISSUE THREAD

**Issue by randomaccess3** [grayfold3d/POSH-Triage#1]
Eventually it would be great to create a session file for Registry Explorer for all of the registry hives.
The session files are text based so shouldn't be too difficult to generate dynamically

**Comment by grayfold3d** [comment]
So by session file, you're referring to the project files(.re_proj) right? I think that's an awesome idea. The text files should be easy to generate.  I guess you'd still have to handle the loading of the transaction logs if the hives were dirty but that still saves a chunk of time, particularly on machines that have multiple user hives.

**Comment by randomaccess3** [comment]
yeah that
Eric said that he was planning on incorporating auto-replay of transactions so users probably wouldn't have to do much after that's done

**Comment by grayfold3d** [comment]
This change has been implemented. Awesome suggestion!
